# Generated by Django 5.1.7 on 2025-03-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='level',
            field=models.CharField(default='EG', max_length=50),
        ),
    ]
